### ISSUE TITLE
CNN 모델 사용시 예측값이 거의 일정한 값이 나왔는데 어떤 이유일까요?

### ISSUE THREAD

**Issue by min9999996** [ClustProject/KUDataRegression#8]

**Comment by Jiyoon52** [comment]
데이터 규모 대비 모델이 대용량인 경우, 과적합되어 일반화 성능이 저하되는 문제가 발생합니다.
MSE를 loss function으로 할당하여 학습하는 경우 과적합 발생시 평균값으로 예측하는 문제가 있으니 drop out이나 모델 용량을 변경하여 일반화 성능 개선이 필요합니다.
